#!/usr/bin/env bash
# World wide web (configuration of subdomains)
if [ "$#" -eq 1 ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        line=$(dig "$subdomain"."$1" | grep -A1 'ANSWER SECTION:' | awk '{print $NF}')
        echo "$subdomain $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
    done
elif [ "$#" -eq 2 ]; then
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk '{print $NF}')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
fi
