#!/usr/bin/env bash
# World wide web (configuration of subdomains)
display_info () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" -q 2 ]
then
  diplay_info "$1" "$2"
else
  display_info "$1" "www"
  display_info "$1" "lb-01"
  display_info "$1" "web-01"
  display_info "$1" "web-02"
fi
