#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting,
#to another page.
apt-get update
apt-get -y install nginx

# Allow HTTP traffic through firewall
ufw allow 'Nginx HTTP'

# Create directory for web files and set permissions
mkdir -p /var/www/html/
chmod -R 755 /var/www

# Create index.html file with "Hello World!" content
echo 'Hello World!' > /var/www/html/index.html

# Configure Nginx server block
cat <<EOF > /etc/nginx/sites-enabled/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        rewrite ^ https://sketchfab.com/bluepeno/models permanent;
    }
}
EOF

# Restart Nginx service
service nginx restart
