#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting,
#to another page.
sudo apt-get update
sudo apt-get install -y nginx 
echo "Hello World!" >  /var/www/html/index.html

echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 https://www.yoytube.com/;
   }
   location / {
        try_files $uri $uri/ =404;
    }


}" > /etc/nginx/sites-available/default

sudo service nginx restart
