#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting,
#to another page.
sudo apt-get update
sudo apt-get install -y nginx 
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html

echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 https://www.google.com/;
   }


}" > /etc/nginx/sites-available/default

sudo service nginx restart
