#!/usr/bin/env bash
# Bash script that:
# Accepts a string as an argument.
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed.
# Ping the IP 5 times.
if [ -z "$1" ]; then
	echo "Usage: $0 {IP_ADDRESS}"
else
	ping -c 5 "${1}"
fi
