#!/usr/bin/env bash
# Configures a server to run Nignx on port 80.
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-enabled/default
service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
