#!/usr/bin/env bash
# This is a Bash script that:
# Creates the file /var/run/myscript.pid containing its PID.
# Displays To infinity and beyond indefinitely.
# Displays I hate the kill command when receiving a SIGTERM signal.
# Displays Y U no love me?! when receiving a SIGINT signal.
# Deletes the file /var/run/myscript.pid and terminates itself
# when receiving a SIGQUIT or SIGTERM signal.

pid_file="/var/run/myscript.pid"
echo "$$" > "$pid_file"

sigterm_handler()
{
	echo "I hate the kill command"
	rm "$pid_file"
	exit 0
}

sigint_handler()
{
	echo "Y U no love me?!"
}

sigquit_handler()
{
	rm "$pud_file"
	exit 0
}

trap 'sigterm_handler' SIGTERM
trap 'sigint_handler' SIGINT
trap 'sigquit_handler' SIGQUIT

while true;
do
	echo "To infinity and beyond"
done
