#!/usr/bin/env bash
# This is a bash script that displays numbers from 1 to 20.
i=1
while [ $i -lt 21 ];
do
	echo $i
	case $i in
		4)
			echo $i
			echo "bad luck from China"
			;;
		9)
			echo $i
			echo "bad luck from Japan"
			;;
		17)
			echo $i
			echo "bad luck from Italy"
			;;

	esac
	((i++))
done
