#!/usr/bin/env bash
# An SSH configuration file for client configuration
CONFIG="Host *
  PasswordAuthentication no
  IdentityFile ~/.ssh/school"
echo "$CONFIG" >> ~/.ssh/config
chmod 600 ~/.ssh/config
